const constants = {
	SET_SCREEN: 		'SET_SCREEN',
	SET_EVENT_KEYS:		'SET_EVENT_KEYS',
	RESET_EVENT_KEYS:	'RESET_EVENT_KEYS',
	SET_CONTEXT: 		'SET_CONTEXT',
	SET_GAME_STATE:		'SET_GAME_STATE',

	SET_TIME_COUNTER:	'SET_TIME_COUNTER',
	SET_TOP_STEPS:		'SET_TOP_STEPS',
	SET_TOP_TIME:		'SET_TOP_TIME',
	SET_CURRENT_STEPS:	'SET_CURRENT_STEPS',
	SET_CURRENT_TIME:	'SET_CURRENT_TIME',
	SET_CURRENT_POSITION:	'SET_CURRENT_POSITION',

	SET_CURRENT_MAZE:	'SET_CURRENT_MAZE'
}

export default constants
