const constants = {
	SET_SCREEN: 		'SET_SCREEN',
	SET_EVENT_KEYS:		'SET_EVENT_KEYS',
	RESET_EVENT_KEYS:	'RESET_EVENT_KEYS',
	SET_CONTEXT: 		'SET_CONTEXT',
	SET_GAME_STATE:		'SET_GAME_STATE',

	SET_TIME_VALUE:		'SET_TIME_VALUE',
	SET_TOP_SCORE:		'SET_TOP_SCORE',
	SET_STEPS:			'SET_STEPS'
}

export default constants
